### PR TITLE
component added: card component

### PR DESCRIPTION
**Pull request by partha8**
hey everyone! I have finally added the card components. It took a lot of effort and a lot of changes to make them look decent. Please share your reviews. Thank you!

### CODE REVIEW

**Review by Dev-AkshatGupta — APPROVED** [review]
LGTM Partha amazing work man . Keep on doing the good work

**Comment by aayushjain-code** [comment]
LGTM clean UI keep working!

**Comment by partha8** [comment]
Thanks @Aayushjain-code . Can you please approve the changes, like akshat did?

**Comment by partha8** [comment]
Got two peer reviews. Merging it into dev branch

**Pull request merged**
