### PR TITLE
components added: image and input

### PR DESCRIPTION
**Pull request by partha8**
Hey everyone, added the image and input component with code snippets. Thank you for reviewing my code.

### CODE REVIEW

**Comment by Dev-AkshatGupta** [comment]
Everything from UI  to code LGTM You can merge it :) . Keep on doing the good work buddy .

**Review by shahbazibnafzal — APPROVED** [review]
Looks good Partha

**Comment by vrinda-mahajan** [comment]
LGTM!👍 You can merge it.

**Comment by vrx29** [comment]
looks good.

**Pull request merged**
